import React, { SyntheticEvent, useState } from "react";
import Head from "next/head";
import { HomeLayout } from "components";
import { useSelector } from "react-redux";
import { Box, Card, CardContent, Grid, Tab } from "@mui/material";
import { ContactsCard, CollectiblesTab, TransactionsTab } from "containers";
import { TabContext, TabList, TabPanel } from "@mui/lab";
import { HomeTab } from "utils";

const Home = () => {
  const st = useSelector((state) => state);
  console.log(st)
  const [value, setValue] = useState<string>(HomeTab.Collectibles);

  const handleChange = (
    _event: SyntheticEvent<Element, Event>,
    newValue: string
  ) => {
    setValue(newValue);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container spacing={2} sx={{ marginTop: "10px" }}>
          <Grid item xs={6}>
            <ContactsCard />
          </Grid>
          <Grid item xs={6}>
            <Card sx={{ minHeight: "99px" }}>
              <CardContent></CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card sx={{ minHeight: "168px" }}>
              <CardContent></CardContent>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <TabContext value={value}>
              <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                <TabList
                  onChange={handleChange}
                  aria-label="lab API tabs example"
                >
                  <Tab
                    label={HomeTab.Collectibles}
                    value={HomeTab.Collectibles}
                  />
                  <Tab
                    label={HomeTab.Transactions}
                    value={HomeTab.Transactions}
                  />
                </TabList>
              </Box>
              <TabPanel value={HomeTab.Collectibles}>
                <CollectiblesTab />
              </TabPanel>
              <TabPanel value={HomeTab.Transactions}>
                <TransactionsTab />
              </TabPanel>
            </TabContext>
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

Home.getLayout = HomeLayout;
export default Home;
