import React, { SyntheticEvent, useState } from "react";
import Head from "next/head";
import { HomeLayout } from "components";
import { useSelector } from "react-redux";
import { Box, Button, Card, CardContent, Grid, Tab, Typography } from "@mui/material";
import { ContactsCard, CollectiblesTab, TransactionsTab } from "containers";
import { TabContext, TabList, TabPanel } from "@mui/lab";
import { HomeTab } from "utils";
import { BoxesIcon } from "../../public/assets/icons/BoxesIcon";
import { NFTIcon } from "../../public/assets/icons/NFTIcon";

const Home = () => {
  const st = useSelector((state) => state);
  console.log(st)
  const [value, setValue] = useState<string>(HomeTab.Collectibles);

  const handleChange = (
    _event: SyntheticEvent<Element, Event>,
    newValue: string
  ) => {
    setValue(newValue);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container spacing={2} sx={{ marginTop: "10px", padding: "10px" }}>
          <Grid item xs={6}>
            <ContactsCard />
          </Grid>
          <Grid item xs={6}>
            <Card sx={{ minHeight: "99px", height: "100%", background: "#885FFF", position: "relative" }}>
              <CardContent sx={{ position: "relative", zIndex: 1 }}>
                <Typography sx={{ fontWeight: "600", fontSize: "16px", color: "#ffffff", }}>web3 Apps</Typography>
                <Button sx={{ background: "#18D7A9", marginTop: "10px", boxShadow: "none", fontSize: 12, padding: "2px 4px", border: "none", textTransform: "capitalize" }} variant="contained" size="small">12 Connected</Button>
              </CardContent>
              <Box component="div" sx={{ position: "absolute", right: 0, top: 0, height: "100%" }}>
                <BoxesIcon />
              </Box>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <Card sx={{ minHeight: "99px", height: "100%", background: "#F7E9FF", position: "relative" }}>
              <CardContent sx={{ position: "relative", zIndex: 1 }}>
                <Typography sx={{ fontWeight: "600", fontSize: "22px", color: "#414047" }}>Start <br /> Creating your <br /> NFT Today</Typography>
                <Button sx={{ background: "#885FFF", marginTop: "10px", boxShadow: "none", fontSize: 16, border: "none", textTransform: "capitalize" }} variant="contained" size="large">Create NFT</Button>
              </CardContent>
              <Box component="div" sx={{ position: "absolute", right: 0, top: 0, height: "100%" }}>
                <NFTIcon/>
              </Box>
            </Card>
          </Grid>
          <Grid item xs={12}>
            <TabContext value={value}>
              <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
                <TabList
                  onChange={handleChange}
                  aria-label="lab API tabs example"
                >
                  <Tab
                    sx={{ flex: "auto", fontWeight: "600", fontSize: "15px", color: "#6F6E73", }}
                    label={HomeTab.Collectibles}
                    value={HomeTab.Collectibles}
                  />
                  <Tab
                    sx={{ flex: "auto", fontWeight: "600", fontSize: "15px", color: "#6F6E73", }}
                    label={HomeTab.Transactions}
                    value={HomeTab.Transactions}
                  />
                </TabList>
              </Box>
              <TabPanel sx={{padding:0}} value={HomeTab.Collectibles}>
                <CollectiblesTab />
              </TabPanel>
              <TabPanel sx={{padding:0}} value={HomeTab.Transactions}>
                <TransactionsTab />
              </TabPanel>
            </TabContext>
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

Home.getLayout = HomeLayout;
export default Home;
